from PyQt5 import QtCore, QtGui, QtWidgets



class MeasurementTab(object):
        self.default_tab = QtWidgets.QWidget()
        self.default_tab.setObjectName("default_tab")
        self.widget = QtWidgets.QWidget(self.default_tab)
        self.widget.setGeometry(QtCore.QRect(22, 22, 341, 431))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setText("Left Side")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setText("Right Side")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.record_left = QtWidgets.QPushButton(self.widget)
        self.record_left.setObjectName("record_left")
        self.gridLayout.addWidget(self.record_left, 1, 0, 1, 1)
        self.record_right = QtWidgets.QPushButton(self.widget)
        self.record_right.setObjectName("record_right")
        self.gridLayout.addWidget(self.record_right, 1, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(8)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(40)
        self.tableWidget.verticalHeader().setDefaultSectionSize(36)
        self.gridLayout.addWidget(self.tableWidget, 2, 0, 1, 2)
        self.measurements_tabs.addTab(self.default_tab, "")
        self.tabWidget.addTab(self.measurementsTab, "")