# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

from tabs.analysis_tab.analysis_tab import AnalysisTab
from tabs.config_tab.config_tab import ConfigTab
from tabs.measurements_tab.measurements_tab import MeasurementsTab
from tabs.patientinfo_tab import PatientInfoTab


class Ui_MainWindow:
    def __init__(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(1000, 650)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")

        self.patient_info_tab = PatientInfoTab()
        self.tabWidget.addTab(self.patient_info_tab, "")

        self.measurement_tab = MeasurementsTab(on_stop_reading_callback=self.update_analysis_tab)
        self.measurement_tab.setObjectName("measurement_tab")
        self.tabWidget.addTab(self.measurement_tab, "")
        self.tabWidget.currentChanged.connect(self.measurement_tab.stop_all_readings)

        self.analysisTab = AnalysisTab()
        self.analysisTab.setObjectName("analysisTab")
        self.tabWidget.addTab(self.analysisTab, "")

        self.configTab = ConfigTab()
        self.configTab.setObjectName("configTab")
        self.tabWidget.addTab(self.configTab, "")

        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tabWidget)
        main_window.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        self.tabWidget.setCurrentIndex(0)
        self.measurement_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.centralwidget.parent().setWindowTitle(_translate("MainWindow", "Algometer Application"))
        self.patient_info_tab.retranslateUi()
        self.measurement_tab.retranslateUi()
        self.analysisTab.retranslateUi()
        self.configTab.retranslateUi()
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.patient_info_tab), _translate("MainWindow", "Patient Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.measurement_tab), _translate("MainWindow", "Measurements"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analysisTab), _translate("MainWindow", "Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configTab), _translate("MainWindow", "Config"))

    def update_analysis_tab(self):
        self.analysisTab.update()
