# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

from tabs.analysis_tab import AnalysisTab
from tabs.config_tab.config_tab import ConfigTab
from tabs.measurements_tab.measurements_tab import MeasurementsTab
from tabs.patientinfo_tab import PatientInfoTab


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")

        self.patient_info_tab = PatientInfoTab()
        self.tabWidget.addTab(self.patient_info_tab, "")

        self.measurement_tab = MeasurementsTab()
        self.measurement_tab.setObjectName("measurement_tab")
        self.tabWidget.addTab(self.measurement_tab, "")
        self.tabWidget.currentChanged.connect(self.measurement_tab.stop_all_readings)

        self.analysisTab = AnalysisTab()
        self.analysisTab.setObjectName("analysisTab")
        self.tabWidget.addTab(self.analysisTab, "")

        self.configTab = ConfigTab()
        self.configTab.setObjectName("configTab")
        self.tabWidget.addTab(self.configTab, "")

        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.measurement_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "Algometer Application"))
        self.patient_info_tab.retranslateUi()
        self.measurement_tab.retranslateUi()
        self.analysisTab.retranslateUi()
        self.configTab.retranslateUi()
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.patient_info_tab), _translate("MainWindow", "Patient Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.measurement_tab), _translate("MainWindow", "Measurements"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analysisTab), _translate("MainWindow", "Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configTab), _translate("MainWindow", "Config"))
